name: Deploy Azure Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/deploy-infra.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep
        uses: azure/bicep-deploy@v1
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: rg-infra-project
          template-file: ./infra/main.bicep
          parameters-file: ./infra/main.dev.bicepparam
          scope: resourceGroup
          type: deployment
          operation: create
          
